CREATE TABLE IF NOT EXISTS role (
  id_role INT AUTO_INCREMENT PRIMARY KEY,
  name_role VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS users (
  id_user INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(30) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL,
  name_display VARCHAR(200) NOT NULL,
  image VARCHAR(100),
  phone VARCHAR(12),
  email VARCHAR(30),
  address VARCHAR(500),
  date_of_brith VARCHAR(12),
  driving_license VARCHAR(20),
  img_driving_license VARCHAR(100),
  sex BIT,
  create_date DATETIME,
  update_date DATETIME,
  id_role INT,
  CONSTRAINT fk_role FOREIGN KEY (id_role) REFERENCES role(id_role)
);

CREATE TABLE IF NOT EXISTS ambulance (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  overview VARCHAR(4000),
  oxygen_tanks INT,
  mobile_beds INT,
  medications VARCHAR(2000),
  license_plates VARCHAR(20) UNIQUE,
  model_year INT,
  status INT,
  maximum_kilometersper_day INT,
  notes VARCHAR(2000),
  address VARCHAR(1000),
  avatar VARCHAR(200),
  images VARCHAR(2000),
  number_of_seats INT,
  bluetooth BIT,
  dash_camera BIT,
  reverse_camera BIT,
  camera360 BIT,
  parking_camera BIT,
  tpms BIT,
  speed_warning BIT,
  gps_locator BIT,
  sunroof BIT,
  dvd_screen BIT,
  driver BIT,
  maps BIT,
  babyseat BIT,
  spare_tire BIT,
  usb BIT,
  impact_sensor BIT,
  bonnet BIT,
  etc BIT,
  airbags BIT,
  manual_transmission_car BIT,
  create_date DATETIME,
  update_date DATETIME,
  driver_id INT,
  CONSTRAINT fk_driver FOREIGN KEY (driver_id) REFERENCES users(id_user)
);
